# Generated by Django 2.1.7 on 2019-03-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_manage', '0003_remove_filemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='path',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
