# Generated by Django 2.1.7 on 2019-04-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_manage', '0004_filemodel_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fileModel',
        ),
    ]
