# Generated by Django 2.1.7 on 2019-04-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files_manage', '0005_delete_filemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload')),
                ('path', models.CharField(max_length=255)),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
