# Generated by Django 2.1.7 on 2019-04-12 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ras_data', '0004_auto_20190309_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='ras_info',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
